/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Entity {
  entity: string
  value: string
  start: number
  end: number
  score: number
}
export interface MaskOptions {
  entities?: Array<string>
  threshold?: number
  placeholder?: string
}
export interface RedactOptions {
  entities?: Array<string>
  threshold?: number
}
export declare function detect(text: string): Array<Entity>
export declare function mask(text: string, options?: MaskOptions | undefined | null): string
export declare function redact(text: string, options?: RedactOptions | undefined | null): string
export declare function detectBatch(texts: Array<string>): Array<Array<Entity>>
